name: Node.js Build
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      store: ${{ steps.install.outputs.store }}

    strategy:
      matrix:
        node: [14.x]

    steps:
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout [blog]
        uses: actions/checkout@v2
        with:
          repository: tiechui1994/blog
          fetch-depth: 5
          ref: master
          persist-credentials: false
          token: ${{secrets.TOKEN}}

      - name: Checkout [note]
        uses: actions/checkout@v2
        with:
          repository: tiechui1994/note
          fetch-depth: 5
          ref: master
          path: static/md/note
          persist-credentials: false

      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: ./node_modules
          key: vercel_note_blog

      - name: Install
        id: install
        run: |
          if [[ -n $(git diff --name-status HEAD^ HEAD|grep -o 'package.json') || ! -e ./node_modules ]];
          then
            echo "::set-output name=store::1"
            rm -rf ./node_modules
            npm install
          fi
        shell: bash

      - name: Store Cache
        uses: actions/cache@v2
        if: ${{ success() && steps.install.outputs.store == 1 }}
        with:
          path: ./node_modules
          key: vercel_note_blog

      - name: Deploy vercel [note]
        if: ${{ success() }}
        run: node src/deploy/vercel.js --project note --domain blog --token ${{secrets.VERCEL}}
