name: Node.js Build
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [14.x]

    steps:
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: Checkout [blog]
        uses: actions/checkout@v2
        with:
          repository: tiechui1994/blog
          fetch-depth: 2
          ref: master
          persist-credentials: false
          token: ${{secrets.TOKEN}}

      - name: Checkout [note]
        uses: actions/checkout@v2
        with:
          repository: tiechui1994/note
          fetch-depth: 2
          ref: master
          path: static/md/note
          persist-credentials: false

      - name: Install
        run: |
          npm install

      - name: Deploy vercel [note]
        if: ${{ success() }}
        run: node src/deploy/vercel.js --project note --domain blog --token ${{secrets.VERCEL}}
