name: output test
on: push

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    outputs:
      key1: ${{steps.output1.outputs.key1}}

    steps:
      - id: output1
        run: |
          echo "::set-output name=key1::'i am key1'"
          echo "key1:${{steps.output1.outputs.key1}}"
      - name: output2
        run: |
          echo "key1:${{steps.output1.outputs.key1}}"
  job2:
    name: job2
    runs-on: ubuntu-latest
    needs: [job1]

    steps:
      - id: use2
        run: |
          echo "use case1: ${{needs.job1.outputs.key1}}"